version: "3.5"

services:
  handbook:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/handbook"
      - "handbook_dependencies:/usr/src/handbook/node_modules"
    env_file:
      - ".env"

volumes:
  handbook_dependencies:
